version: '3.9'
services:
  app:
    build:
      context: .
    ports:
      - "80:80"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: aman
      DB_PASSWORD: test@1234
      DB_NAME: devops_db
    volumes:
      - ./devops_backup:/app/devops_backup
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: devops_db
      MYSQL_USER: aman
      MYSQL_PASSWORD: test@1234
    volumes:
      - ./devops_backup:/var/lib/mysql
      - ./db_form.sql:/docker-entrypoint-initdb.d/db_form.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

