apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: production-env
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data/mysql"

