apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
  namespace: production-env
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: manual

