apiVersion: v1
kind: Service
metadata:
  name: form-app-service
  namespace: production-env
spec:
  selector:
    app: form-application
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP


